apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashenpost-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flashenpost
  template:
    metadata:
      labels:
        app: flashenpost
    spec:
      containers:
        - name: flashenpost-container
          image: strm/helloworld-http:latest
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 1
            failureThreshold: 2
